from fastapi import FastAPI, Depends, HTTPException, status, Query
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List, Optional

import models
import schemas
import crud
from database import engine, get_db, DB_TYPE
from seed import seed_database

# Create database tables automatically upon server start
models.Base.metadata.create_all(bind=engine)

# Auto seed sample incidents if database is fresh
try:
    seed_database()
except Exception as e:
    print(f"[STARTUP WARNING] Seed check failed: {e}")

# Initialize FastAPI application
app = FastAPI(
    title="ResQ Hub - Emergency Response Platform API",
    description="REST API backend for ResQ Hub DBMS Review 2 Prototype",
    version="1.0.0"
)

# Enable CORS (Cross-Origin Resource Sharing) for React Frontend
origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "*"  # Allows connection from any dev client during evaluation
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- API ENDPOINTS ---

@app.get("/", tags=["Health"])
def read_root():
    """
    Root Endpoint - API Status check.
    """
    return {
        "project": "ResQ Hub - Intelligent Emergency Response Platform",
        "status": "Online",
        "review": "Review 2 DBMS Prototype",
        "database": DB_TYPE,
        "docs_url": "http://localhost:8000/docs"
    }

@app.get("/health", tags=["Health"])
def health_check(db: Session = Depends(get_db)):
    """
    Health check endpoint verifying FastAPI and database active connection.
    """
    try:
        # Simple test query
        db.execute(models.Incident.__table__.select().limit(1))
        return {"status": "healthy", "database_connection": "active", "database_type": DB_TYPE}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database connection error: {str(e)}"
        )

# 1. CREATE Incident (POST /incidents)
@app.post(
    "/incidents",
    response_model=schemas.IncidentResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["Incidents"],
    summary="Register a new emergency incident"
)
def create_new_incident(incident: schemas.IncidentCreate, db: Session = Depends(get_db)):
    """
    Register a new emergency incident.
    1. Validates request body using IncidentCreate Pydantic schema.
    2. Inserts new record into PostgreSQL 'incidents' table using SQLAlchemy.
    3. Returns created record with autogenerated ID and timestamps.
    """
    return crud.create_incident(db=db, incident=incident)

# 2. READ ALL Incidents (GET /incidents)
@app.get(
    "/incidents",
    response_model=List[schemas.IncidentResponse],
    tags=["Incidents"],
    summary="Fetch list of all emergency incidents"
)
def read_all_incidents(
    skip: int = 0,
    limit: int = 100,
    status: Optional[str] = Query(None, description="Filter by status (Pending, In Progress, Resolved)"),
    priority: Optional[str] = Query(None, description="Filter by priority (Low, Medium, High, Critical)"),
    db: Session = Depends(get_db)
):
    """
    Fetch all incidents stored in PostgreSQL.
    Supports optional pagination (skip, limit) and filtering (status, priority).
    """
    incidents = crud.get_incidents(db=db, skip=skip, limit=limit, status=status, priority=priority)
    return incidents

# 3. READ SINGLE Incident (GET /incidents/{id})
@app.get(
    "/incidents/{incident_id}",
    response_model=schemas.IncidentResponse,
    tags=["Incidents"],
    summary="Fetch specific incident details by ID"
)
def read_incident_by_id(incident_id: int, db: Session = Depends(get_db)):
    """
    Fetch details of a specific emergency incident using its primary key ID.
    Returns 404 error if incident is not found.
    """
    db_incident = crud.get_incident_by_id(db=db, incident_id=incident_id)
    if db_incident is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Incident with ID {incident_id} not found"
        )
    return db_incident

# 4. UPDATE Incident (PUT /incidents/{id})
@app.put(
    "/incidents/{incident_id}",
    response_model=schemas.IncidentResponse,
    tags=["Incidents"],
    summary="Update an existing emergency incident"
)
def update_existing_incident(
    incident_id: int,
    incident_update: schemas.IncidentUpdate,
    db: Session = Depends(get_db)
):
    """
    Update details or status of an existing emergency incident.
    Returns updated incident record or 404 error if ID doesn't exist.
    """
    updated = crud.update_incident(db=db, incident_id=incident_id, incident_update=incident_update)
    if updated is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Cannot update. Incident with ID {incident_id} not found"
        )
    return updated

# 5. DELETE Incident (DELETE /incidents/{id})
@app.delete(
    "/incidents/{incident_id}",
    status_code=status.HTTP_200_OK,
    tags=["Incidents"],
    summary="Delete an emergency incident"
)
def delete_existing_incident(incident_id: int, db: Session = Depends(get_db)):
    """
    Delete an emergency incident from PostgreSQL database.
    """
    success = crud.delete_incident(db=db, incident_id=incident_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Cannot delete. Incident with ID {incident_id} not found"
        )
    return {"message": f"Incident with ID {incident_id} deleted successfully", "id": incident_id}
